[2022-08-02 15:04:09,499] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pokea.respond 2022-08-02T14:50:00+00:00 [queued]>
[2022-08-02 15:04:09,766] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pokea.respond 2022-08-02T14:50:00+00:00 [queued]>
[2022-08-02 15:04:09,779] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 15:04:09,802] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-08-02 15:04:09,835] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 15:04:10,009] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): respond> on 2022-08-02T14:50:00+00:00
[2022-08-02 15:04:10,061] {standard_task_runner.py:51} INFO - Started process 28093 to run task
[2022-08-02 15:04:10,142] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'pokea', 'respond', '2022-08-02T14:50:00+00:00', '--job-id', '40', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pokea.py', '--cfg-path', '/tmp/tmpnhp6_g61']
[2022-08-02 15:04:10,206] {standard_task_runner.py:76} INFO - Job 40: Subtask respond
[2022-08-02 15:04:11,054] {logging_mixin.py:103} INFO - Running <TaskInstance: pokea.respond 2022-08-02T14:50:00+00:00 [running]> on host b4dcda255553
[2022-08-02 15:04:13,590] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=pokea
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T14:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-02T14:50:00+00:00
[2022-08-02 15:04:13,607] {python.py:118} INFO - Done. Returned value was: Greet Responded Again
[2022-08-02 15:04:13,878] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=pokea, task_id=respond, execution_date=20220802T145000, start_date=20220802T150409, end_date=20220802T150413
[2022-08-02 15:04:14,222] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-02 15:04:14,300] {local_task_job.py:118} INFO - Task exited with return code 0
