[2022-08-02 15:10:22,031] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pokea.respond 2022-08-02T15:00:00+00:00 [queued]>
[2022-08-02 15:10:22,185] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pokea.respond 2022-08-02T15:00:00+00:00 [queued]>
[2022-08-02 15:10:22,187] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 15:10:22,189] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-08-02 15:10:22,191] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 15:10:22,250] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): respond> on 2022-08-02T15:00:00+00:00
[2022-08-02 15:10:22,264] {standard_task_runner.py:51} INFO - Started process 1786 to run task
[2022-08-02 15:10:22,284] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'pokea', 'respond', '2022-08-02T15:00:00+00:00', '--job-id', '49', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pokea.py', '--cfg-path', '/tmp/tmpql7xm5mr']
[2022-08-02 15:10:22,300] {standard_task_runner.py:76} INFO - Job 49: Subtask respond
[2022-08-02 15:10:22,554] {logging_mixin.py:103} INFO - Running <TaskInstance: pokea.respond 2022-08-02T15:00:00+00:00 [running]> on host b4dcda255553
[2022-08-02 15:10:22,859] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=pokea
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T15:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-02T15:00:00+00:00
[2022-08-02 15:10:22,864] {python.py:118} INFO - Done. Returned value was: Greet Responded Again
[2022-08-02 15:10:23,003] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=pokea, task_id=respond, execution_date=20220802T150000, start_date=20220802T151022, end_date=20220802T151023
[2022-08-02 15:10:23,162] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-02 15:10:23,221] {local_task_job.py:118} INFO - Task exited with return code 0
