[2022-08-02 16:30:11,443] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pokea.respond 2022-08-02T16:20:00+00:00 [queued]>
[2022-08-02 16:30:11,468] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pokea.respond 2022-08-02T16:20:00+00:00 [queued]>
[2022-08-02 16:30:11,468] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 16:30:11,469] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-08-02 16:30:11,469] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 16:30:11,485] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): respond> on 2022-08-02T16:20:00+00:00
[2022-08-02 16:30:11,489] {standard_task_runner.py:51} INFO - Started process 13325 to run task
[2022-08-02 16:30:11,493] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'pokea', 'respond', '2022-08-02T16:20:00+00:00', '--job-id', '140', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pokea.py', '--cfg-path', '/tmp/tmpch1ou__f']
[2022-08-02 16:30:11,497] {standard_task_runner.py:76} INFO - Job 140: Subtask respond
[2022-08-02 16:30:11,558] {logging_mixin.py:103} INFO - Running <TaskInstance: pokea.respond 2022-08-02T16:20:00+00:00 [running]> on host b4dcda255553
[2022-08-02 16:30:11,631] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=pokea
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T16:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-02T16:20:00+00:00
[2022-08-02 16:30:11,632] {python.py:118} INFO - Done. Returned value was: Greet Responded Again
[2022-08-02 16:30:11,670] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=pokea, task_id=respond, execution_date=20220802T162000, start_date=20220802T163011, end_date=20220802T163011
[2022-08-02 16:30:11,712] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-02 16:30:11,746] {local_task_job.py:118} INFO - Task exited with return code 0
