[2022-08-02 14:50:10,293] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pokea.respond 2022-08-02T14:40:00+00:00 [queued]>
[2022-08-02 14:50:10,341] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pokea.respond 2022-08-02T14:40:00+00:00 [queued]>
[2022-08-02 14:50:10,342] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 14:50:10,342] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-08-02 14:50:10,343] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 14:50:10,365] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): respond> on 2022-08-02T14:40:00+00:00
[2022-08-02 14:50:10,370] {standard_task_runner.py:51} INFO - Started process 1356 to run task
[2022-08-02 14:50:10,384] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'pokea', 'respond', '2022-08-02T14:40:00+00:00', '--job-id', '33', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pokea.py', '--cfg-path', '/tmp/tmpuuenow1z']
[2022-08-02 14:50:10,389] {standard_task_runner.py:76} INFO - Job 33: Subtask respond
[2022-08-02 14:50:10,479] {logging_mixin.py:103} INFO - Running <TaskInstance: pokea.respond 2022-08-02T14:40:00+00:00 [running]> on host b4dcda255553
[2022-08-02 14:50:10,569] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=pokea
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T14:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-02T14:40:00+00:00
[2022-08-02 14:50:10,571] {python.py:118} INFO - Done. Returned value was: Greet Responded Again
[2022-08-02 14:50:10,625] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=pokea, task_id=respond, execution_date=20220802T144000, start_date=20220802T145010, end_date=20220802T145010
[2022-08-02 14:50:10,679] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-02 14:50:10,711] {local_task_job.py:118} INFO - Task exited with return code 0
